name: Test action

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: 'Create test issue #1'
        uses: randlabs/createissue-action@v1
        with:
          title: 'Test issue #1'
          labels: test
          milestone: 1
          filename: .github/__tests__/SAMPLE_ISSUE.md
          update-existing: true
          search-type: all
          search-title: 'test\sissue\s.*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}